# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uM2EXPyULFhJy7x6Af08twVlcqRBMz5
"""

price1 = 100
price2 = 200
tax = 1.1

def total():
    return price1 + price2

print (total() * tax)